# Generated by Django 4.1 on 2024-07-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impute_model", models.CharField(max_length=20)),
                ("predict_model", models.CharField(max_length=20)),
                ("predict_window_size", models.FloatField()),
            ],
        ),
    ]
