# Generated by Django 4.1 on 2024-07-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("data", models.TextField()),
                ("mask", models.TextField()),
                ("predicted_data", models.TextField(default="")),
                ("predicted_mask", models.TextField(default="")),
                ("time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
