# Generated by Django 4.1 on 2024-08-10 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrainResult",
        ),
    ]
