# Generated by Django 4.1 on 2024-08-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0002_delete_trainresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("dataset", models.CharField(max_length=64)),
                ("train_time", models.TimeField()),
                ("predict_time", models.TimeField()),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("SMAPE", models.FloatField()),
            ],
        ),
    ]
