# Generated by Django 4.1 on 2024-08-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0004_alter_trainingresult_predict_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predata",
            name="time",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
