# Generated by Django 4.1 on 2024-08-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0005_alter_predata_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalyresult",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imputeresult",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
